export const fontDefs = {
    sans: {
        name: "Inter",
        family: '"Inter", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    thin: {
        name: "Inter (Light)",
        family: '"Inter", sans-serif',
        weightNormal: 300,
        weightBold: 500,
    },
    poppins: {
        name: "Poppins",
        family: '"Poppins", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    montserrat: {
        name: "Montserrat",
        family: '"Montserrat", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    raleway: {
        name: "Raleway",
        family: '"Raleway", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    quicksand: {
        name: "Quicksand",
        family: '"Quicksand", sans-serif',
        weightNormal: 500,
        weightBold: 700,
    },
    lato: {
        name: "Lato",
        family: '"Lato", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    roboto: {
        name: "Roboto",
        family: '"Roboto", sans-serif',
        weightNormal: 400,
        weightBold: 500,
    },
    open: {
        name: "Open Sans",
        family: '"Open Sans", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    orbitron: {
        name: "Orbitron",
        family: '"Orbitron", sans-serif',
        weightNormal: 500,
        weightBold: 800,
    },
    play: {
        name: "Play",
        family: '"Play", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    archivo: {
        name: "Archivo Black",
        family: '"Archivo Black", sans-serif',
        weightNormal: 400,
        weightBold: 400,
    },
    press: {
        name: "Press Start 2P",
        family: '"Press Start 2P", cursive',
        weightNormal: 400,
        weightBold: 400,
    },
    russo: {
        name: "Russo One",
        family: '"Russo One", sans-serif',
        weightNormal: 400,
        weightBold: 400,
    },
    serif: {
        name: "Playfair Display",
        family: '"Playfair Display", serif',
        weightNormal: 400,
        weightBold: 600,
    },
    merri: {
        name: "Merriweather",
        family: '"Merriweather", serif',
        weightNormal: 300,
        weightBold: 700,
    },
    pt: {
        name: "PT Serif",
        family: '"PT Serif", serif',
        weightNormal: 400,
        weightBold: 700,
    },
    lora: {
        name: "Lora",
        family: '"Lora", serif',
        weightNormal: 400,
        weightBold: 600,
    },
    fira: {
        name: "Fira Code",
        family: '"Fira Code", monospace',
        weightNormal: 400,
        weightBold: 600,
    },
    jetbrains: {
        name: "JetBrains Mono",
        family: '"JetBrains Mono", monospace',
        weightNormal: 400,
        weightBold: 600,
    },
    hack: {
        name: "Hack",
        family: '"Hack", "Dejavu Sans Mono", monospace',
        weightNormal: 400,
        weightBold: 700,
    },
    source: {
        name: "Source Code Pro",
        family: '"Source Code Pro", monospace',
        weightNormal: 400,
        weightBold: 600,
    },
    space: {
        name: "Space Mono",
        family: '"Space Mono", monospace',
        weightNormal: 400,
        weightBold: 700,
    },
    ubuntu: {
        name: "Ubuntu Mono",
        family: '"Ubuntu Mono", monospace',
        weightNormal: 400,
        weightBold: 700,
    },
    inconsol: {
        name: "Inconsolata",
        family: '"Inconsolata", monospace',
        weightNormal: 400,
        weightBold: 700,
    },
    ibm: {
        name: "IBM Plex Mono",
        family: '"IBM Plex Mono", monospace',
        weightNormal: 400,
        weightBold: 600,
    },

    // Industry Standard & Stylish Fonts
    helvetica: {
        name: "Helvetica",
        family: '"Helvetica Neue", "Helvetica", Arial, sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    arial: {
        name: "Arial",
        family: 'Arial, "Helvetica Neue", Helvetica, sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    georgia: {
        name: "Georgia",
        family: 'Georgia, "Times New Roman", serif',
        weightNormal: 400,
        weightBold: 700,
    },
    times: {
        name: "Times New Roman",
        family: '"Times New Roman", Times, serif',
        weightNormal: 400,
        weightBold: 700,
    },
    basker: {
        name: "Baskerville",
        family: '"Baskerville", "Times New Roman", serif',
        weightNormal: 400,
        weightBold: 700,
    },
    gill: {
        name: "Gill Sans",
        family: '"Gill Sans", "Gill Sans MT", Calibri, sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    futura: {
        name: "Futura",
        family: '"Futura", "Trebuchet MS", Arial, sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    didot: {
        name: "Didot",
        family: 'Didot, "Times New Roman", serif',
        weightNormal: 400,
        weightBold: 700,
    },
    bodoni: {
        name: "Bodoni MT",
        family: '"Bodoni MT", Didot, "Times New Roman", serif',
        weightNormal: 400,
        weightBold: 700,
    },
    rockwell: {
        name: "Rockwell",
        family: 'Rockwell, "Courier Bold", Courier, Georgia, serif',
        weightNormal: 400,
        weightBold: 700,
    },
    gotham: {
        name: "Gotham",
        family: '"Gotham", "Helvetica Neue", Helvetica, Arial, sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    proxima: {
        name: "Proxima Nova",
        family: '"Proxima Nova", "Helvetica Neue", Helvetica, Arial, sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    acumin: {
        name: "Acumin Pro",
        family: '"Acumin Pro", "Helvetica Neue", Arial, sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },

    // Modern Stylish Display Fonts
    bebas: {
        name: "Bebas Neue",
        family: '"Bebas Neue", cursive',
        weightNormal: 400,
        weightBold: 400,
    },
    oswald: {
        name: "Oswald",
        family: '"Oswald", "Roboto", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    nunito: {
        name: "Nunito",
        family: '"Nunito", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    rubik: {
        name: "Rubik",
        family: '"Rubik", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    manrope: {
        name: "Manrope",
        family: '"Manrope", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    dm: {
        name: "DM Sans",
        family: '"DM Sans", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    figtree: {
        name: "Figtree",
        family: '"Figtree", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    instrument: {
        name: "Instrument Serif",
        family: '"Instrument Serif", serif',
        weightNormal: 400,
        weightBold: 400,
    },
    cardo: {
        name: "Cardo",
        family: '"Cardo", serif',
        weightNormal: 400,
        weightBold: 700,
    },

    // Professional Fonts
    glyphter: {
        name: "Glyphter",
        family: '"Glyphter", "Helvetica Neue", Arial, sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    thein: {
        name: "Theinhardt",
        family: '"Theinhardt", "Helvetica Neue", Arial, sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    azimuth: {
        name: "Azimuth",
        family: '"Azimuth", "Helvetica Neue", Arial, sans-serif',
        weightNormal: 400,
        weightBold: 800,
    },
};