export const fontDefs = {
    sans: {
        name: "Inter",
        family: '"Inter", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    thin: {
        name: "Inter (Light)",
        family: '"Inter", sans-serif',
        weightNormal: 300,
        weightBold: 500,
    },
    poppins: {
        name: "Poppins",
        family: '"Poppins", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    montserrat: {
        name: "Montserrat",
        family: '"Montserrat", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    raleway: {
        name: "Raleway",
        family: '"Raleway", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    quicksand: {
        name: "Quicksand",
        family: '"Quicksand", sans-serif',
        weightNormal: 500,
        weightBold: 700,
    },
    lato: {
        name: "Lato",
        family: '"Lato", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    roboto: {
        name: "Roboto",
        family: '"Roboto", sans-serif',
        weightNormal: 400,
        weightBold: 500,
    },
    open: {
        name: "Open Sans",
        family: '"Open Sans", sans-serif',
        weightNormal: 400,
        weightBold: 600,
    },
    orbitron: {
        name: "Orbitron",
        family: '"Orbitron", sans-serif',
        weightNormal: 500,
        weightBold: 800,
    },
    play: {
        name: "Play",
        family: '"Play", sans-serif',
        weightNormal: 400,
        weightBold: 700,
    },
    archivo: {
        name: "Archivo Black",
        family: '"Archivo Black", sans-serif',
        weightNormal: 400,
        weightBold: 400,
    },
    press: {
        name: "Press Start 2P",
        family: '"Press Start 2P", cursive',
        weightNormal: 400,
        weightBold: 400,
    },
    russo: {
        name: "Russo One",
        family: '"Russo One", sans-serif',
        weightNormal: 400,
        weightBold: 400,
    },
    serif: {
        name: "Playfair Display",
        family: '"Playfair Display", serif',
        weightNormal: 400,
        weightBold: 600,
    },
    merri: {
        name: "Merriweather",
        family: '"Merriweather", serif',
        weightNormal: 300,
        weightBold: 700,
    },
    pt: {
        name: "PT Serif",
        family: '"PT Serif", serif',
        weightNormal: 400,
        weightBold: 700,
    },
    lora: {
        name: "Lora",
        family: '"Lora", serif',
        weightNormal: 400,
        weightBold: 600,
    },
    fira: {
        name: "Fira Code",
        family: '"Fira Code", monospace',
        weightNormal: 400,
        weightBold: 600,
    },
    jetbrains: {
        name: "JetBrains Mono",
        family: '"JetBrains Mono", monospace',
        weightNormal: 400,
        weightBold: 600,
    },
    hack: {
        name: "Hack",
        family: '"Hack", "Dejavu Sans Mono", monospace',
        weightNormal: 400,
        weightBold: 700,
    },
    source: {
        name: "Source Code Pro",
        family: '"Source Code Pro", monospace',
        weightNormal: 400,
        weightBold: 600,
    },
    space: {
        name: "Space Mono",
        family: '"Space Mono", monospace',
        weightNormal: 400,
        weightBold: 700,
    },
    ubuntu: {
        name: "Ubuntu Mono",
        family: '"Ubuntu Mono", monospace',
        weightNormal: 400,
        weightBold: 700,
    },
    inconsol: {
        name: "Inconsolata",
        family: '"Inconsolata", monospace',
        weightNormal: 400,
        weightBold: 700,
    },
    ibm: {
        name: "IBM Plex Mono",
        family: '"IBM Plex Mono", monospace',
        weightNormal: 400,
        weightBold: 600,
    },
};