export const paletteDefs = {
    // --- DESIGNER ---
    cat_mocha: {
        name: "Cat Mocha",
        category: "Designer",
        type: "solid",
        primary: "#cba6f7",
        accent: "#f5c2e7",
        isDark: false,
    },
    cat_latte: {
        name: "Cat Latte",
        category: "Designer",
        type: "solid",
        primary: "#8839ef",
        accent: "#7287fd",
        fgForce: "#ffffff",
        isDark: true,
    },
    tokyo: {
        name: "Tokyo",
        category: "Designer",
        type: "solid",
        primary: "#7aa2f7",
        accent: "#bb9af7",
        isDark: true,
    },
    dracula: {
        name: "Dracula",
        category: "Designer",
        type: "solid",
        primary: "#bd93f9",
        accent: "#ff79c6",
        isDark: true,
    },
    nord: {
        name: "Nord",
        category: "Designer",
        type: "solid",
        primary: "#81a1c1",
        accent: "#88c0d0",
        isDark: true,
    },
    monokai: {
        name: "Monokai",
        category: "Designer",
        type: "solid",
        primary: "#a6e22e",
        accent: "#f92672",
        isDark: true,
    },
    matrix: {
        name: "Matrix",
        category: "Designer",
        type: "solid",
        primary: "#00ff41",
        accent: "#008f11",
        fgForce: "#000",
        isDark: false,
    },
    one_dark: {
        name: "One Dark",
        category: "Designer",
        type: "solid",
        primary: "#98c379",
        accent: "#61afef",
        isDark: true,
    },
    gruvbox: {
        name: "Gruvbox",
        category: "Designer",
        type: "solid",
        primary: "#d79921",
        accent: "#fb4934",
        isDark: true,
    },
    solarized: {
        name: "Solarized",
        category: "Designer",
        type: "solid",
        primary: "#b58900",
        accent: "#2aa198",
        isDark: true,
    },
    synth_pop: {
        name: "Synth Pop",
        category: "Designer",
        type: "gradient",
        primary: "linear-gradient(to right, #ff00cc, #333399)",
        accent: "#00ffcc",
        glow: "#ff00cc",
        isDark: true,
    },

    // --- GRADIENTS ---
    vapor: {
        name: "Vapor",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #ff71ce 0%, #01cdfe 100%)",
        accent: "#fffb96",
        glow: "#ff71ce",
        isDark: false,
    },
    gold_rush: {
        name: "Gold Rush",
        category: "Gradient",
        type: "gradient",
        primary:
            "linear-gradient(135deg, #bf953f 0%, #fcf6ba 50%, #b38728 100%)",
        accent: "#ffd700",
        glow: "#fbf5b7",
        fgForce: "#000",
        isDark: false,
    },
    sunset: {
        name: "Sunset",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #c2410c 0%, #be185d 100%)",
        accent: "#fb923c",
        glow: "#db2777",
        isDark: true,
    },
    oceanic: {
        name: "Oceanic",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #0e7490 0%, #1d4ed8 100%)",
        accent: "#22d3ee",
        glow: "#3b82f6",
        isDark: true,
    },
    hyper: {
        name: "Hyper",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #db2777 0%, #7c3aed 100%)",
        accent: "#f472b6",
        glow: "#8b5cf6",
        isDark: true,
    },
    aurora: {
        name: "Aurora",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #047857 0%, #1d4ed8 100%)",
        accent: "#34d399",
        glow: "#3b82f6",
        isDark: true,
    },
    midnight_g: {
        name: "Midnight G",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #312e81 0%, #020617 100%)",
        accent: "#818cf8",
        glow: "#4f46e5",
        isDark: true,
    },
    cotton: {
        name: "Cotton",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #db2777 0%, #2563eb 100%)",
        accent: "#f472b6",
        glow: "#60a5fa",
        isDark: true,
    },
    obsidian: {
        name: "Obsidian",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #000000 0%, #374151 100%)",
        accent: "#9ca3af",
        glow: "#e5e7eb",
        isDark: true,
    },
    sublime: {
        name: "Sublime",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #e11d48 0%, #4f46e5 100%)",
        accent: "#fb7185",
        glow: "#818cf8",
        isDark: true,
    },
    horizon: {
        name: "Horizon",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #0c4a6e 0%, #a16207 100%)",
        accent: "#38bdf8",
        glow: "#eab308",
        isDark: true,
    },
    cosmic_n: {
        name: "Cosmic",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #d946ef 0%, #4338ca 100%)",
        accent: "#f0abfc",
        glow: "#818cf8",
        isDark: true,
    },
    lush: {
        name: "Lush",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #15803d 0%, #65a30d 100%)",
        accent: "#4ade80",
        glow: "#a3e635",
        isDark: true,
    },
    firewatch: {
        name: "Firewatch",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #991b1b 0%, #ea580c 100%)",
        accent: "#f87171",
        glow: "#fb923c",
        isDark: true,
    },
    synthwave: {
        name: "Synth",
        category: "Gradient",
        type: "gradient",
        primary: "linear-gradient(135deg, #2b213a 0%, #ff71ce 100%)",
        accent: "#01cdfe",
        glow: "#ff71ce",
        isDark: true,
    },

    // --- SEASONS ---
    autumn: {
        name: "Autumn",
        category: "Seasons",
        type: "solid",
        primary: "#d35400",
        accent: "#f39c12",
        isDark: true,
    },
    winter: {
        name: "Winter",
        category: "Seasons",
        type: "solid",
        primary: "#2c3e50",
        accent: "#ecf0f1",
        isDark: true,
    },
    spring: {
        name: "Spring",
        category: "Seasons",
        type: "solid",
        primary: "#2ecc71",
        accent: "#f1c40f",
        isDark: true,
    },
    summer: {
        name: "Summer",
        category: "Seasons",
        type: "solid",
        primary: "#e67e22",
        accent: "#e74c3c",
        isDark: true,
    },

    // --- MONOCHROME ---
    zinc: {
        name: "Zinc",
        category: "Monochrome",
        type: "solid",
        primary: "#27272a",
        accent: "#a1a1aa",
        isDark: true,
    },
    slate: {
        name: "Slate",
        category: "Monochrome",
        type: "solid",
        primary: "#1e293b",
        accent: "#94a3b8",
        isDark: true,
    },
    stone: {
        name: "Stone",
        category: "Monochrome",
        type: "solid",
        primary: "#292524",
        accent: "#a8a29e",
        isDark: true,
    },
    ash: {
        name: "Ash",
        category: "Monochrome",
        type: "solid",
        primary: "#52525b",
        accent: "#d4d4d8",
        isDark: true,
    },
    carbon: {
        name: "Carbon",
        category: "Monochrome",
        type: "solid",
        primary: "#171717",
        accent: "#52525b",
        isDark: true,
    },
    void: {
        name: "Void",
        category: "Monochrome",
        type: "solid",
        primary: "#000000",
        accent: "#333333",
        isDark: true,
    },
    platinum: {
        name: "Platinum",
        category: "Monochrome",
        type: "solid",
        primary: "#e5e7eb",
        accent: "#6b7280",
        fgForce: "#000",
        isDark: false,
    },
    ghost: {
        name: "Ghost",
        category: "Monochrome",
        type: "solid",
        primary: "#f3f4f6",
        accent: "#9ca3af",
        fgForce: "#000",
        isDark: false,
    },
    silver: {
        name: "Silver",
        category: "Monochrome",
        type: "solid",
        primary: "#cbd5e1",
        accent: "#64748b",
        fgForce: "#000",
        isDark: false,
    },
    paper: {
        name: "Paper",
        category: "Monochrome",
        type: "solid",
        primary: "#f5f5f4",
        accent: "#78716c",
        fgForce: "#000",
        isDark: false,
    },

    // --- SOFT / PASTEL ---
    iceberg: {
        name: "Iceberg",
        category: "Soft",
        type: "solid",
        primary: "#cffafe",
        accent: "#22d3ee",
        fgForce: "#000",
        isDark: false,
    },
    lavender: {
        name: "Lavender",
        category: "Soft",
        type: "solid",
        primary: "#e9d5ff",
        accent: "#c084fc",
        fgForce: "#000",
        isDark: false,
    },
    rose: {
        name: "Rose",
        category: "Soft",
        type: "solid",
        primary: "#ffe4e6",
        accent: "#fda4af",
        fgForce: "#000",
        isDark: false,
    },
    mint: {
        name: "Mint",
        category: "Soft",
        type: "solid",
        primary: "#d1fae5",
        accent: "#34d399",
        fgForce: "#000",
        isDark: false,
    },
    peach: {
        name: "Peach",
        category: "Soft",
        type: "solid",
        primary: "#ffedd5",
        accent: "#fb923c",
        fgForce: "#000",
        isDark: false,
    },
    sky: {
        name: "Sky",
        category: "Soft",
        type: "solid",
        primary: "#e0f2fe",
        accent: "#38bdf8",
        fgForce: "#000",
        isDark: false,
    },
    cream: {
        name: "Cream",
        category: "Soft",
        type: "solid",
        primary: "#fef3c7",
        accent: "#d97706",
        fgForce: "#000",
        isDark: false,
    },
    lilac: {
        name: "Lilac",
        category: "Soft",
        type: "solid",
        primary: "#fae8ff",
        accent: "#d946ef",
        fgForce: "#000",
        isDark: false,
    },
    matcha: {
        name: "Matcha",
        category: "Soft",
        type: "solid",
        primary: "#dcfce7",
        accent: "#16a34a",
        fgForce: "#000",
        isDark: false,
    },
    baby_blue: {
        name: "Baby Blue",
        category: "Soft",
        type: "solid",
        primary: "#dbeafe",
        accent: "#2563eb",
        fgForce: "#000",
        isDark: false,
    },

    // --- VIBRANT ---
    cyberpunk: {
        name: "Cyberpunk",
        category: "Vibrant",
        type: "solid",
        primary: "#00ffea",
        accent: "#ff00ff",
        fgForce: "#000",
        isDark: true,
    },
    laser: {
        name: "Laser",
        category: "Vibrant",
        type: "solid",
        primary: "#facc15",
        accent: "#eab308",
        fgForce: "#000",
        isDark: false,
    },
    crimson: {
        name: "Crimson",
        category: "Vibrant",
        type: "solid",
        primary: "#991b1b",
        accent: "#ef4444",
        isDark: true,
    },
    pumpkin: {
        name: "Pumpkin",
        category: "Vibrant",
        type: "solid",
        primary: "#ea580c",
        accent: "#f97316",
        isDark: true,
    },
    bumblebee: {
        name: "Bumblebee",
        category: "Vibrant",
        type: "solid",
        primary: "#eab308",
        accent: "#eab308",
        fgForce: "#000",
        isDark: false,
    },
    candy: {
        name: "Candy",
        category: "Vibrant",
        type: "solid",
        primary: "#ec4899",
        accent: "#3b82f6",
        isDark: true,
    },
    rust: {
        name: "Rust",
        category: "Vibrant",
        type: "solid",
        primary: "#7c2d12",
        accent: "#c2410c",
        isDark: true,
    },
    poison: {
        name: "Poison",
        category: "Vibrant",
        type: "solid",
        primary: "#a3e635",
        accent: "#84cc16",
        fgForce: "#000",
        isDark: true,
    },
    hot_pink: {
        name: "Hot Pink",
        category: "Vibrant",
        type: "solid",
        primary: "#db2777",
        accent: "#f472b6",
        isDark: true,
    },
    ultraviolet: {
        name: "Ultra",
        category: "Vibrant",
        type: "solid",
        primary: "#7c3aed",
        accent: "#a78bfa",
        isDark: true,
    },
    electric: {
        name: "Electric",
        category: "Vibrant",
        type: "solid",
        primary: "#2563eb",
        accent: "#3b82f6",
        isDark: true,
    },
    magma: {
        name: "Magma",
        category: "Vibrant",
        type: "solid",
        primary: "#ef4444",
        accent: "#fca5a5",
        isDark: true,
    },

    // --- LUXURY ---
    royal: {
        name: "Royal",
        category: "Luxury",
        type: "solid",
        primary: "#4a0404",
        accent: "#ffd700",
        isDark: true,
    },
    gold: {
        name: "Gold",
        category: "Luxury",
        type: "solid",
        primary: "#b45309",
        accent: "#fcd34d",
        isDark: true,
    },
    metallic: {
        name: "Metallic Red",
        category: "Luxury",
        type: "gradient",
        primary:
            "linear-gradient(135deg, #7f1d1d 0%, #ef4444 50%, #7f1d1d 100%)",
        accent: "#f87171",
        glow: "#ef4444",
        isDark: true,
    },
    marble: {
        name: "Marble",
        category: "Luxury",
        type: "solid",
        primary: "#f8f9fa",
        accent: "#212529",
        fgForce: "#000",
        isDark: false,
    },
};