import {
    Activity,
    Ban,
    CloudRain,
    Disc,
    Dna,
    FileCode,
    Flame,
    Grid,
    Grip,
    HeartCrack,
    Sparkles,
    Star,
    Snowflake,
    Network,
    Zap as ZapIcon,
} from "lucide-react";

export const particleOptions = [
    { id: "off", name: "Off", icon: Ban },
    { id: "pulse", name: "Pulse", icon: Activity },
    { id: "nodes", name: "Nodes", icon: Network },
    { id: "matrix", name: "Matrix", icon: FileCode },
    { id: "rain", name: "Rain", icon: CloudRain },
    { id: "dust", name: "Dust", icon: Sparkles },
    { id: "snow", name: "Snow", icon: Snowflake },
    { id: "bubbles", name: "Bubbles", icon: Disc },
    { id: "stars", name: "Stars", icon: Star },
    { id: "confetti", name: "Confetti", icon: HeartCrack },
    { id: "fireflies", name: "Fireflies", icon: Flame },
    { id: "grid", name: "Grid", icon: Grip },
    { id: "dna", name: "DNA", icon: Dna },
    { id: "speed", name: "Speed", icon: ZapIcon },
];