import {
    Ghost,
    Box,
    CloudRain,
    Leaf,
    Command,
    ZapOff,
    Globe,
    Cpu,
    Lightbulb,
    Square,
    Scan,
    Layers,
    Gamepad2,
    Layout,
    Circle,
    Shield,
    Hexagon,
    Hash,
    Triangle,
    Zap,
    HeartCrack,
    Grid,
    Droplet,
    Terminal,
    FileText,
} from "lucide-react";

export const styles = {
    glassmorphism: {
        name: "Glassmorphism",
        icon: Ghost,
        vars: {
            "--radius": "24px",
            "--border": "1px solid var(--border-color)",
            "--shadow": "0 8px 32px 0 rgba(31, 38, 135, 0.15)",
            "--backdrop": "blur(16px) saturate(180%)",
            "--bg-panel-override": "rgba(255, 255, 255, 0.05)",
            "--btn-radius": "12px",
        },
        isGlass: true,
    },
    neumorphism: {
        name: "Neumorphism",
        icon: Box,
        vars: {
            "--radius": "20px",
            "--border": "none",
            "--bg-panel-override": "var(--bg-app)",
            "--shadow": "var(--neu-shadow)",
            "--backdrop": "none",
            "--btn-radius": "12px",
        },
        dynamicVars: (isDark) => ({
            "--neu-shadow": isDark
                ? "5px 5px 10px #0b1221, -5px -5px 10px #1a2842"
                : "9px 9px 18px #d1d5db, -9px -9px 18px #ffffff",
        }),
    },
    frutigerAero: {
        name: "Frutiger Aero",
        icon: CloudRain,
        vars: {
            "--radius": "18px",
            "--border": "1px solid rgba(255, 255, 255, 0.5)",
            "--shadow":
                "0 10px 30px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.8)",
            "--backdrop": "blur(15px)",
            "--bg-panel-override":
                "linear-gradient(to bottom, rgba(255,255,255,0.9) 0%, rgba(255,255,255,0.6) 50%, rgba(255,255,255,0.4) 51%, rgba(255,255,255,0.8) 100%)",
            "--btn-radius": "24px",
            "--text-main": "#0f172a",
            "--input-bg": "rgba(255,255,255,0.7)",
        },
        isGlass: true,
        forceContrast: true,
    },
    solarpunkStyle: {
        name: "Solarpunk",
        icon: Leaf,
        vars: {
            "--radius": "24px 4px 24px 4px",
            "--border": "2px solid var(--primary)",
            "--shadow": "0 10px 20px -5px var(--primary)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "16px 4px 16px 4px",
        },
    },
    system7: {
        name: "System 7",
        icon: Command,
        vars: {
            "--radius": "2px",
            "--border": "2px solid black",
            "--shadow": "4px 4px 0px black",
            "--backdrop": "none",
            "--bg-panel-override": "#ffffff",
            "--text-main": "#000000",
            "--text-muted": "#333333",
            "--btn-radius": "2px",
            "--input-bg": "#ffffff",
            "--font-family": '"Chicago", sans-serif',
        },
        forcedScheme: "light",
        forceContrast: true,
    },
    glitch: {
        name: "Glitch",
        icon: ZapOff,
        vars: {
            "--radius": "0px",
            "--border": "1px solid var(--text-main)",
            "--shadow":
                "3px 3px 0px rgba(255, 0, 0, 0.7), -3px -3px 0px rgba(0, 255, 255, 0.7)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "0px",
            "--btn-border": "2px solid var(--text-main)",
            "--clip-path":
                "polygon(5% 0, 100% 0, 100% 90%, 95% 100%, 0 100%, 0 10%)",
            "--transform": "skew(-1deg)",
        },
        forcedScheme: "dark",
        forceContrast: true,
    },
    chrome: {
        name: "Y2K Chrome",
        icon: Globe,
        vars: {
            "--radius": "16px",
            "--border": "1px solid rgba(255,255,255,0.6)",
            "--shadow":
                "0 15px 35px rgba(0,0,0,0.2), inset 0 0 15px rgba(255,255,255,0.5)",
            "--backdrop": "blur(5px)",
            "--bg-panel-override":
                "linear-gradient(135deg, rgba(255,255,255,0.6) 0%, rgba(255,255,255,0.3) 50%, rgba(255,255,255,0.1) 51%, rgba(255,255,255,0.4) 100%)",
            "--btn-radius": "99px",
            "--input-bg": "rgba(255,255,255,0.4)",
            "--text-main": "#000000",
            "--text-muted": "#333333",
        },
        forceContrast: true,
    },
    cyberdeck: {
        name: "Cyberdeck",
        icon: Cpu,
        vars: {
            "--radius": "2px",
            "--border": "1px solid var(--primary)",
            "--shadow":
                "0 0 20px rgba(0,0,0,0.5), inset 0 0 20px rgba(0,0,0,0.2)",
            "--backdrop": "blur(10px)",
            "--bg-panel-override":
                "linear-gradient(135deg, rgba(10,10,10,0.95) 0%, rgba(20,20,20,0.98) 100%)",
            "--btn-radius": "2px",
            "--clip-path":
                "polygon(15px 0, 100% 0, 100% calc(100% - 15px), calc(100% - 15px) 100%, 0 100%, 0 15px)",
            "--input-bg": "rgba(0,0,0,0.5)",
        },
        forcedScheme: "dark",
        forceContrast: true,
    },
    neon: {
        name: "Neon",
        icon: Lightbulb,
        vars: {
            "--radius": "12px",
            "--border": "2px solid var(--accent)",
            "--shadow": "0 0 15px var(--accent), inset 0 0 15px var(--accent)",
            "--backdrop": "blur(5px)",
            "--bg-panel-override": "rgba(0, 0, 0, 0.8)",
            "--btn-radius": "8px",
            "--text-main": "#ffffff",
            "--text-muted": "#aaaaaa",
        },
        forcedScheme: "dark",
        forceContrast: true,
    },
    slab: {
        name: "Slab",
        icon: Square,
        vars: {
            "--radius": "0px",
            "--border": "8px solid var(--text-main)",
            "--shadow": "12px 12px 0px var(--primary)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "0px",
        },
    },
    holographic: {
        name: "Holographic",
        icon: Scan,
        vars: {
            "--radius": "16px",
            "--border": "1px solid rgba(255, 255, 255, 0.3)",
            "--shadow":
                "0 0 30px rgba(0, 255, 255, 0.2), inset 0 0 20px rgba(255, 0, 255, 0.1)",
            "--backdrop": "blur(20px) hue-rotate(15deg)",
            "--bg-panel-override":
                "linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0.05))",
            "--btn-radius": "8px",
        },
        isGlass: true,
        forcedScheme: "dark",
    },
    acrylic: {
        name: "Acrylic (Win11)",
        icon: Layers,
        vars: {
            "--radius": "8px",
            "--border": "1px solid var(--border-color)",
            "--shadow": "0 4px 24px -1px rgba(0,0,0,0.1)",
            "--backdrop": "blur(20px) saturate(120%)",
            "--bg-panel-override": "rgba(255, 255, 255, 0.3)",
            "--btn-radius": "4px",
        },
        isGlass: true,
    },
    gameboy: {
        name: "Gameboy",
        icon: Gamepad2,
        vars: {
            "--radius": "10px 10px 40px 10px",
            "--border": "3px solid rgba(0,0,0,0.2)",
            "--shadow":
                "5px 5px 15px rgba(0,0,0,0.3), inset 2px 2px 5px rgba(255,255,255,0.1), inset -2px -2px 5px rgba(0,0,0,0.2)",
            "--backdrop": "none",
            "--btn-radius": "50px",
            "--font-family": '"Press Start 2P", monospace',
            "--input-bg": "#9bbc0f",
            "--input-text": "#0f380f",
            "--placeholder-color": "rgba(15, 56, 15, 0.75)",
            "--shadow-input": "inset 2px 2px 4px rgba(0,0,0,0.6)",
            "--btn-sec-bg": "#9bbc0f",
            "--btn-sec-text": "#0f380f",
            "--btn-sec-border": "none",
            "--btn-sec-shadow": "inset 2px 2px 4px rgba(0,0,0,0.6)",
        },
        forcedScheme: "light",
        forceContrast: true,
    },
    retro95: {
        name: "Retro 95",
        icon: Layout,
        vars: {
            "--radius": "0px",
            "--border": "2px solid transparent",
            "--shadow":
                "inset 2px 2px 0px #ffffff, inset -2px -2px 0px #000000",
            "--backdrop": "none",
            "--bg-panel-override": "var(--retro-bg)",
            "--text-main": "var(--retro-text)",
            "--text-muted": "var(--retro-text-muted)",
            "--btn-radius": "0px",
            "--input-bg": "var(--bg-panel)",
        },
        dynamicVars: (isDark) => ({
            "--retro-bg": isDark ? "#374151" : "#c0c0c0",
            "--retro-text": isDark ? "#ffffff" : "#000000",
            "--retro-text-muted": isDark ? "#d1d5db" : "#404040",
        }),
    },
    claymorphism: {
        name: "Claymorphism",
        icon: Circle,
        vars: {
            "--radius": "32px",
            "--border": "none",
            "--shadow":
                "12px 12px 24px rgba(0,0,0,0.1), inset -8px -8px 8px rgba(0,0,0,0.05), inset 8px 8px 16px rgba(255,255,255,0.4)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "24px",
        },
    },
    skeuomorphism: {
        name: "Skeuomorphism",
        icon: Shield,
        vars: {
            "--radius": "12px",
            "--border": "1px solid var(--border-color)",
            "--shadow":
                "inset 0 1px 0 rgba(255,255,255,0.6), 0 4px 8px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.1)",
            "--backdrop": "none",
            "--bg-panel-override":
                "linear-gradient(to bottom, var(--bg-panel), var(--bg-app))",
            "--btn-radius": "6px",
        },
    },
    flat2: {
        name: "Flat 2.0",
        icon: Square,
        vars: {
            "--radius": "8px",
            "--border": "1px solid var(--border-color)",
            "--shadow": "0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "6px",
        },
    },
    materialYou: {
        name: "Material You",
        icon: Circle,
        vars: {
            "--radius": "28px",
            "--border": "none",
            "--shadow":
                "0 1px 2px rgba(0,0,0,0.3), 0 1px 3px 1px rgba(0,0,0,0.15)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "999px",
        },
    },
    neobrutalism: {
        name: "Neo-Brutalism",
        icon: Hexagon,
        vars: {
            "--radius": "0px",
            "--border": "3px solid var(--text-main)",
            "--shadow": "6px 6px 0px 0px var(--text-main)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "0px",
        },
    },
    brutalist: {
        name: "Brutalist (Raw)",
        icon: Hash,
        vars: {
            "--radius": "0px",
            "--border": "1px solid var(--text-main)",
            "--shadow": "none",
            "--backdrop": "none",
            "--bg-panel-override": "transparent",
            "--btn-radius": "0px",
            "--font-family": '"Courier New", monospace',
            "--input-bg": "transparent",
        },
    },
    bauhaus: {
        name: "Bauhaus",
        icon: Triangle,
        vars: {
            "--radius": "0px",
            "--border": "4px solid var(--text-main)",
            "--shadow": "10px 10px 0px 0px var(--primary)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "100px",
            "--input-bg": "var(--bg-app)",
        },
    },
    aurora: {
        name: "Aurora",
        icon: Zap,
        vars: {
            "--radius": "24px",
            "--border": "1px solid rgba(255,255,255,0.1)",
            "--shadow": "0 0 60px -5px var(--accent)",
            "--backdrop": "blur(40px)",
            "--bg-panel-override": "rgba(0,0,0,0.3)",
            "--btn-radius": "16px",
        },
        isGlass: true,
    },
    vaporwave: {
        name: "Vaporwave",
        icon: HeartCrack,
        vars: {
            "--radius": "0px",
            "--border": "2px solid var(--accent)",
            "--shadow": "0 0 15px var(--accent)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--vapor-bg)",
            "--text-main": "var(--vapor-text)",
            "--clip-path": "polygon(0 0, 100% 0, 100% 85%, 95% 100%, 0 100%)",
            "--btn-radius": "0px",
        },
        dynamicVars: (isDark) => ({
            "--vapor-bg": isDark ? "#2b213a" : "#ffffff",
            "--vapor-text": isDark ? "#ff71ce" : "#000000",
        }),
    },
    bento: {
        name: "Bento Grid",
        icon: Grid,
        vars: {
            "--radius": "32px",
            "--border": "1px solid var(--border-color)",
            "--shadow": "0 4px 12px rgba(0,0,0,0.03)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "16px",
        },
    },
    minimalism: {
        name: "Minimalism",
        icon: Droplet,
        vars: {
            "--radius": "0px",
            "--border": "2px solid var(--border-color)",
            "--shadow": "none",
            "--backdrop": "none",
            "--bg-panel-override": "transparent",
            "--btn-radius": "0px",
        },
    },
    terminal: {
        name: "Terminal",
        icon: Terminal,
        vars: {
            "--radius": "0px",
            "--border": "1px solid var(--accent)",
            "--shadow": "0 0 15px var(--accent)",
            "--backdrop": "none",
            "--bg-panel-override": "#000000",
            "--text-main": "var(--accent)",
            "--text-muted": "var(--accent)",
            "--input-bg": "#000000",
            "--btn-radius": "0px",
            "--font-family": '"Fira Code", monospace',
        },
        forcedScheme: "dark",
        forceContrast: true,
    },
    paper: {
        name: "Paper Sketch",
        icon: FileText,
        vars: {
            "--radius": "255px 15px 225px 15px / 15px 225px 15px 255px",
            "--border": "2px solid var(--text-main)",
            "--shadow": "2px 3px 0px rgba(0,0,0,0.1)",
            "--backdrop": "none",
            "--bg-panel-override": "var(--bg-panel)",
            "--btn-radius": "255px 15px 225px 15px / 15px 225px 15px 255px",
        },
    },
};